import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>QuickQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <div className="wrapper">
      <div class="title-text">
        <div class="title login">Login</div>
        <div class="title signup">Sign up</div>
      </div>
      <div class="form-container">
        <div class="slide-controls">
          <input type="radio" name="slide" id="login" checked/>
          <input type="radio" name="slide" id="signup"/>
          <label for="login" class="slide login">Login</label>
          <label for="signup" class="slide signup">Signup</label>
          <div class="slider-tab"></div>
        </div>
        <div class="form-inner">
          <form action="#" class="login">
            <div class="field">
              <input type="text" placeholder="Email Address" required/>
            </div>
            <div class="field">
              <input type="password" placeholder="Password" required/>
            </div>
            <div class="pass-link"><a href="#">Forgot password?</a></div>
            <div class="field btn">
              <div class="btn-layer"></div>
              <input type="submit" value="Login"/>
            </div>
            <div class="signup-link">New to QuickQ? <a href="">Signup now</a></div>
          </form>
          <form action="#" class="signup">
            <div class="field">
              <input type="text" placeholder="Email Address" required/>
            </div>
            <div class="field">
              <input type="password" placeholder="Password" required/>
            </div>
            <div class="field">
              <input type="password" placeholder="Confirm password" required/>
            </div>
            <div class="field btn">
              <div class="btn-layer"></div>
              <input type="submit" value="Signup"/>
            </div>
          </form>
        </div>
      </div>
    </div>
      </main>
      </div>

  )
}
