import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Sub.module.css'

export default function Subscribe() {
  return (
    <div className={styles.container}>
      <Head>
        <title>QuickQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.bttt}><h2>Subscribe to a Queue</h2></div>
    
      <main className={styles.main}>
      <div className="wrapper">
      <div class="title-text">
        <div class="title login">Enter Code</div>
      </div>
      <div class="form-container">
        <div class="form-inner">
          <form action="#" class="login">
            <div class="field">
              <input type="text" placeholder="Enter Code" required/>
            </div>
        <div class="field btn">
              <div class="btn-layer"></div>
              <input type="submit" value="Subscribe"/>
            </div>
              </form>
        </div>
      </div>
    </div>
      </main>
      </div>

  )
}
